application: nusxchange
version: 1

runtime: python27

api_version: 1

threadsafe: true



handlers:


- url: /stylesheets

  static_dir: stylesheets



- url: /images
  static_dir: images

- url: /_ah/login_required
  script: login.app

# Twitter Bootstrap

- url: /bootstrap/fonts/(.*\.ttf)
  static_files: bootstrap/fonts/\1
  upload: bootstrap/fonts/(.*\.ttf)
  mime_type: application/x-font-ttf

- url: /bootstrap/fonts/(.*\.eot)
  static_files: bootstrap/fonts/\1
  upload: bootstrap/fonts/(.*\.eot)
  mime_type: application/vnd.ms-fontobject

- url: /bootstrap/fonts/(.*\.woff)
  static_files: bootstrap/fonts/\1
  upload: bootstrap/fonts/(.*\.woff)
  mime_type: application/x-font-woff


- url: /bootstrap

  static_dir: bootstrap

- url: /js
  static_dir: js
# Handler for front page

- url: /.*
  script: nusxchange.app

libraries:

- name: jinja2

  version: latest
